#!/bin/sh
# vim: filetype=i3config

# super key
set $mod Mod4

# font for window titles
font pango:Fira Sans Condensed 10

# reload the configuration file
bindsym $mod+Shift+c reload

# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

# exit i3 (logs out of X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Really exit i3?' -B 'Exit i3' 'i3-msg exit'"

#########################
# window borders/titles #
#########################

# borders
for_window [class=".*"] border pixel 3
hide_edge_borders smart

for_window [class=".*"] title_format " <span size=\\"smaller\\">%title</span>"

# class                 border  bground text    indicator child_border
client.focused          #4C7899 #285577 #FFFFFF #2E9EF4   #285577
client.focused_inactive #333333 #5F676A #FFFFFF #484E50   #5F676A
client.unfocused        #333333 #222222 #888888 #292D2E   #222222
client.urgent           #2F343A #900000 #FFFFFF #900000   #900000
client.placeholder      #000000 #0C0C0C #FFFFFF #000000   #0C0C0C

client.background       #FFFFFF

bindsym --release button2 kill

##################
# gaps gaps gaps #
##################

# initial gaps
gaps inner 13
gaps outer 0
gaps bottom 41

# gap adjustment
bindsym $mod+minus gaps inner all plus 5
bindsym $mod+equal gaps inner all minus 5
bindsym $mod+Shift+minus gaps outer all plus 5
bindsym $mod+Shift+equal gaps outer all minus 5

# show/hide polybar
# bindsym $mod+Shift+p exec "polybar-msg cmd hide" gaps bottom all set 0
# bindsym $mod+p exec "polybar-msg cmd show" gaps bottom all set 28

############
# keyboard #
############

# function keys
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioPlay exec --no-startup-id mpc toggle
bindsym XF86AudioNext exec --np-startup-id mpc next
bindsym XF86AudioPrev exec --no-startup-id mpc prev
bindsym Print exec --no-startup-id flameshot gui

# airplane mode
# bindsym XF86RFKill exec -- bash -e "rfkill list | grep -q '\byes\b' && rfkill unblock all || rfkill block all"

################
# mouse config #
################

# Use Mouse+$mod to drag floating windows
floating_modifier $mod

# focus follows mouse
focus_follows_mouse yes

# kill focused window
bindsym $mod+Shift+q kill

############
# programs #
############

bindsym $mod+Return exec --no-startup-id alacritty

bindsym $mod+d exec --no-startup-id "bash -c 'cd $HOME/.config/rofi/scripts && ./launcher.sh'"
bindsym $mod+Shift+d exec --no-startup-id "$HOME/.local/bin/rofi-open command"
bindsym $mod+Mod1+d exec --no-startup-id "$HOME/.local/bin/rofi-open emoji"

################
# window focus #
################

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# arrow keys
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

###################
# window movement #
###################

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# arrow keys
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

bindsym $mod+Shift+s sticky toggle

##############
# workspaces #
##############

set $ws1 1
set $ws2 2
set $ws3 3
set $ws4 4
set $ws5 5
set $ws6 6
set $ws7 7
set $ws8 8
set $ws9 9
set $ws10 10

set $mv move container
set $ws workspace number

# switch to workspace
bindsym $mod+1 $ws $ws1
bindsym $mod+2 $ws $ws2
bindsym $mod+3 $ws $ws3
bindsym $mod+4 $ws $ws4
bindsym $mod+5 $ws $ws5
bindsym $mod+6 $ws $ws6
bindsym $mod+7 $ws $ws7
bindsym $mod+8 $ws $ws8
bindsym $mod+9 $ws $ws9
bindsym $mod+0 $ws $ws10

# move focused container to workspace
bindsym $mod+Shift+1 $mv to $ws $ws1
bindsym $mod+Shift+2 $mv to $ws $ws2
bindsym $mod+Shift+3 $mv to $ws $ws3
bindsym $mod+Shift+4 $mv to $ws $ws4
bindsym $mod+Shift+5 $mv to $ws $ws5
bindsym $mod+Shift+6 $mv to $ws $ws6
bindsym $mod+Shift+7 $mv to $ws $ws7
bindsym $mod+Shift+8 $mv to $ws $ws8
bindsym $mod+Shift+9 $mv to $ws $ws9
bindsym $mod+Shift+0 $mv to $ws $ws10

# place apps on certain workspaces
assign [class="firefoxdeveloperedition"] $ws1
assign [class="discord"] $ws3
assign [class="cantata"] $ws4
assign [class="google play music desktop player"] $ws4

###################
# window resizing #
###################

# add resize keybindings in place of mode
bindsym $mod+Control+Left resize shrink width 5 px or 5
bindsym $mod+Control+Down resize grow height 5 px or 5
bindsym $mod+Control+Up resize shrink height 5 px or 5
bindsym $mod+Control+Right resize grow width 5 px or 5
bindsym $mod+Shift+Control+Left resize shrink width 1 px or 1
bindsym $mod+Shift+Control+Down resize grow height 1 px or 1
bindsym $mod+Shift+Control+Up resize shrink height 1 px or 1
bindsym $mod+Shift+Control+Right resize grow width 1 px or 1

#############
# processes #
#############

exec_always --no-startup-id $HOME/.fehbg
# exec_always --no-startup-id picom -b
exec --no-startup-id "bash -c 'sleep 2 && pulseaudio -k && sleep 1 && pulseaudio -D'"
# exec --no-startup-id pulseeffects --gapplication-service
exec --no-startup-id dunst
exec --no-startup-id flameshot
exec --no-startup-id nm-applet
exec --no-startup-id mpd
#exec --no-startup-id keepassxc
exec --no-startup-id "bash -c 'sleep 15 && nextcloud'"
exec_always --no-startup-id "bash -c 'sleep 4 && $HOME/.config/polybar/launch.sh'"
